# Generated by Django 5.2.8 on 2026-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_section_subtag"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="ollama", max_length=32)),
                ("ollama_base_url", models.URLField(default="http://localhost:11434")),
                (
                    "generation_model",
                    models.CharField(default="llama3.2", max_length=128),
                ),
                (
                    "embedding_model",
                    models.CharField(default="nomic-embed-text", max_length=128),
                ),
                (
                    "reranker_model",
                    models.CharField(
                        default="cross-encoder/ms-marco-MiniLM-L-6-v2", max_length=255
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "gemini_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VectorIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.TextField(unique=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["file_path"],
            },
        ),
    ]
