# Generated by Django 5.2.8 on 2026-04-05 11:41

from django.db import migrations, models


def assign_section_positions(apps, schema_editor):
    """Backfill section positions per module using creation order."""

    _ = schema_editor
    Section = apps.get_model("api", "Section")
    module_info_ids = (
        Section.objects.order_by().values_list("module_info_id", flat=True).distinct()
    )

    for module_info_id in module_info_ids:
        sections = Section.objects.filter(module_info_id=module_info_id).order_by("id")
        for position, section in enumerate(sections):
            section.position = position
            section.save(update_fields=["position"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_ragconfig_vectorindex"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddField(
            model_name="section",
            name="note_order",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="section",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(assign_section_positions, migrations.RunPython.noop),
    ]
