[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    { name = "Aleks Tacconi", email = "aleks.tacconi@gmail.com" }
]
license = { text = "GPLv3" }
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "django >=5.0,<6.0",
    "djangorestframework >=3.15,<4.0",
    "djangorestframework-simplejwt >=5.3,<6.0",
    "python-dotenv >=1.0,<2.0",
    "django-cors-headers >=4.3,<5.0",
    "requests >=2.31,<3.0",
    "drf-spectacular >=0.27,<0.30",
    "drf-spectacular-sidecar >=2024.7,<2026.0",
]

[dependency-groups]
dev = [
    "pylint >=3.0,<4.0",
    "django-types >=0.22,<0.23",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

