/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * API for an Obsidian integrated TODO app
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { Grade, PatchedGrade } from "./api.schemas";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const gradesList = <TData = AxiosResponse<Grade[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/grades/`, options);
};
export const gradesCreate = <TData = AxiosResponse<Grade>>(
  grade: NonReadonly<Grade>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/grades/`, grade, options);
};
export const gradesRetrieve = <TData = AxiosResponse<Grade>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/grades/${id}/`, options);
};
export const gradesUpdate = <TData = AxiosResponse<Grade>>(
  id: number,
  grade: NonReadonly<Grade>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/grades/${id}/`, grade, options);
};
export const gradesPartialUpdate = <TData = AxiosResponse<Grade>>(
  id: number,
  patchedGrade: NonReadonly<PatchedGrade>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(`/api/grades/${id}/`, patchedGrade, options);
};
export const gradesDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/grades/${id}/`, options);
};
export type GradesListResult = AxiosResponse<Grade[]>;
export type GradesCreateResult = AxiosResponse<Grade>;
export type GradesRetrieveResult = AxiosResponse<Grade>;
export type GradesUpdateResult = AxiosResponse<Grade>;
export type GradesPartialUpdateResult = AxiosResponse<Grade>;
export type GradesDestroyResult = AxiosResponse<void>;
