/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * API for an Obsidian integrated TODO app
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { ModuleInfo, PatchedModuleInfo } from "./api.schemas";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const moduleInfoList = <TData = AxiosResponse<ModuleInfo[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/module-info/`, options);
};
export const moduleInfoCreate = <TData = AxiosResponse<ModuleInfo>>(
  moduleInfo: NonReadonly<ModuleInfo>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/module-info/`, moduleInfo, options);
};
export const moduleInfoRetrieve = <TData = AxiosResponse<ModuleInfo>>(
  primaryTag: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/module-info/${primaryTag}/`, options);
};
export const moduleInfoUpdate = <TData = AxiosResponse<ModuleInfo>>(
  primaryTag: number,
  moduleInfo: NonReadonly<ModuleInfo>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(
    `/api/module-info/${primaryTag}/`,
    moduleInfo,
    options,
  );
};
export const moduleInfoPartialUpdate = <TData = AxiosResponse<ModuleInfo>>(
  primaryTag: number,
  patchedModuleInfo: NonReadonly<PatchedModuleInfo>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `/api/module-info/${primaryTag}/`,
    patchedModuleInfo,
    options,
  );
};
export const moduleInfoDestroy = <TData = AxiosResponse<void>>(
  primaryTag: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/module-info/${primaryTag}/`, options);
};
export type ModuleInfoListResult = AxiosResponse<ModuleInfo[]>;
export type ModuleInfoCreateResult = AxiosResponse<ModuleInfo>;
export type ModuleInfoRetrieveResult = AxiosResponse<ModuleInfo>;
export type ModuleInfoUpdateResult = AxiosResponse<ModuleInfo>;
export type ModuleInfoPartialUpdateResult = AxiosResponse<ModuleInfo>;
export type ModuleInfoDestroyResult = AxiosResponse<void>;
