/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * API for an Obsidian integrated TODO app
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { Note, PatchedNote } from "./api.schemas";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const notesList = <TData = AxiosResponse<Note[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/notes/`, options);
};
export const notesCreate = <TData = AxiosResponse<Note>>(
  note: NonReadonly<Note>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/notes/`, note, options);
};
export const notesRetrieve = <TData = AxiosResponse<Note>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/notes/${id}/`, options);
};
export const notesUpdate = <TData = AxiosResponse<Note>>(
  id: number,
  note: NonReadonly<Note>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/notes/${id}/`, note, options);
};
export const notesPartialUpdate = <TData = AxiosResponse<Note>>(
  id: number,
  patchedNote: NonReadonly<PatchedNote>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(`/api/notes/${id}/`, patchedNote, options);
};
export const notesDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/notes/${id}/`, options);
};
export type NotesListResult = AxiosResponse<Note[]>;
export type NotesCreateResult = AxiosResponse<Note>;
export type NotesRetrieveResult = AxiosResponse<Note>;
export type NotesUpdateResult = AxiosResponse<Note>;
export type NotesPartialUpdateResult = AxiosResponse<Note>;
export type NotesDestroyResult = AxiosResponse<void>;
