/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * API for an Obsidian integrated TODO app
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { PatchedPrimaryTag, PrimaryTag } from "./api.schemas";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const primaryTagsList = <TData = AxiosResponse<PrimaryTag[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/primary-tags/`, options);
};
export const primaryTagsCreate = <TData = AxiosResponse<PrimaryTag>>(
  primaryTag: NonReadonly<PrimaryTag>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/primary-tags/`, primaryTag, options);
};
export const primaryTagsRetrieve = <TData = AxiosResponse<PrimaryTag>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/primary-tags/${id}/`, options);
};
export const primaryTagsUpdate = <TData = AxiosResponse<PrimaryTag>>(
  id: number,
  primaryTag: NonReadonly<PrimaryTag>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/primary-tags/${id}/`, primaryTag, options);
};
export const primaryTagsPartialUpdate = <TData = AxiosResponse<PrimaryTag>>(
  id: number,
  patchedPrimaryTag: NonReadonly<PatchedPrimaryTag>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(
    `/api/primary-tags/${id}/`,
    patchedPrimaryTag,
    options,
  );
};
export const primaryTagsDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/primary-tags/${id}/`, options);
};
export type PrimaryTagsListResult = AxiosResponse<PrimaryTag[]>;
export type PrimaryTagsCreateResult = AxiosResponse<PrimaryTag>;
export type PrimaryTagsRetrieveResult = AxiosResponse<PrimaryTag>;
export type PrimaryTagsUpdateResult = AxiosResponse<PrimaryTag>;
export type PrimaryTagsPartialUpdateResult = AxiosResponse<PrimaryTag>;
export type PrimaryTagsDestroyResult = AxiosResponse<void>;
