/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * API for an Obsidian integrated TODO app
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { PatchedSection, Section } from "./api.schemas";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const sectionsList = <TData = AxiosResponse<Section[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/sections/`, options);
};
export const sectionsCreate = <TData = AxiosResponse<Section>>(
  section: NonReadonly<Section>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/sections/`, section, options);
};
export const sectionsRetrieve = <TData = AxiosResponse<Section>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/sections/${id}/`, options);
};
export const sectionsUpdate = <TData = AxiosResponse<Section>>(
  id: number,
  section: NonReadonly<Section>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/sections/${id}/`, section, options);
};
export const sectionsPartialUpdate = <TData = AxiosResponse<Section>>(
  id: number,
  patchedSection: NonReadonly<PatchedSection>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(`/api/sections/${id}/`, patchedSection, options);
};
export const sectionsDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/sections/${id}/`, options);
};
export type SectionsListResult = AxiosResponse<Section[]>;
export type SectionsCreateResult = AxiosResponse<Section>;
export type SectionsRetrieveResult = AxiosResponse<Section>;
export type SectionsUpdateResult = AxiosResponse<Section>;
export type SectionsPartialUpdateResult = AxiosResponse<Section>;
export type SectionsDestroyResult = AxiosResponse<void>;
