/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * API
 * API for an Obsidian integrated TODO app
 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { NoteURL, PatchedNoteURL } from "./api.schemas";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export const urlsList = <TData = AxiosResponse<NoteURL[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/urls/`, options);
};
export const urlsCreate = <TData = AxiosResponse<NoteURL>>(
  noteURL: NonReadonly<NoteURL>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/urls/`, noteURL, options);
};
export const urlsRetrieve = <TData = AxiosResponse<NoteURL>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/urls/${id}/`, options);
};
export const urlsUpdate = <TData = AxiosResponse<NoteURL>>(
  id: number,
  noteURL: NonReadonly<NoteURL>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/urls/${id}/`, noteURL, options);
};
export const urlsPartialUpdate = <TData = AxiosResponse<NoteURL>>(
  id: number,
  patchedNoteURL: NonReadonly<PatchedNoteURL>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.patch(`/api/urls/${id}/`, patchedNoteURL, options);
};
export const urlsDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.delete(`/api/urls/${id}/`, options);
};
export type UrlsListResult = AxiosResponse<NoteURL[]>;
export type UrlsCreateResult = AxiosResponse<NoteURL>;
export type UrlsRetrieveResult = AxiosResponse<NoteURL>;
export type UrlsUpdateResult = AxiosResponse<NoteURL>;
export type UrlsPartialUpdateResult = AxiosResponse<NoteURL>;
export type UrlsDestroyResult = AxiosResponse<void>;
