name: CI Pipeline

on:
  push:
    branches:
      - main
      - Issue-2
  pull_request:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    name: Run python linting

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt-get install make
        make backend-install

    - name: Run pylint
      run: make backend-lint 

  lint-react:
    runs-on: ubuntu-latest
    name: Run react linting

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install make
        make frontend-install

    - name: Run eslint
      run: make frontend-lint

  test-python:
    runs-on: ubuntu-latest
    name: Run pytest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt-get install make
        make backend-install

    - name: Run pytest
      run: make backend-test
