name: CI Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Pylint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt-get install make
        cd backend && make install

    - name: Run pylint
      run: cd backend && make lint

  eslint:
    runs-on: ubuntu-latest
    name: Eslint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install make
        cd frontend && make install

    - name: Run eslint
      run: | 
        cd frontend && make lint

  pytest:
    runs-on: ubuntu-latest
    name: Pytest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt-get install make
        cd backend && make install

    - name: Run pytest
      run: | 
        cd backend && make test

